# Generated by Django 4.0.10 on 2023-10-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digit',
            name='user_correction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
